language: ruby
rvm:
- 2.3.1
before_install:
- curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.0.3
- gem install bundler -v 1.11.2
install:
  - chef exec bundle install --jobs=3 --retry=3
before_script: chef exec bundle exec rake setup_test_environment
script: chef exec bundle exec rake except_kitchen
notifications:
  slack:
    secure: pVpfyW1c6WeO31NXpZzYxDUKwMV/EqGFboKbqRW4lVAxuK4bJ2OlUhcUfnv8CAXhBtN+GvK8MpMDa4MdfrMMh9Wqd6WnGCT9UWVBfyE/9ejk4GFjBuhsXoqWBzRbGBSnnsU2gWciUEQQ39jQ2lXANTSthVVJYNGot1UTqaMXA9o=
